conda-incubator/conda-store-ui

src/features/environments/components/EnvironmentDropdown.tsx
Click on the (+) button should open create a new environment tab instead of collapsing all namespaces.
=> Create an environment using (+) button without collapsing namespaces

src/components/VersionSelect.tsx, src/features/channels/components/ChannelsEdit.tsx, src/features/environmentCreate/components/CreateEnvironmentPackages.tsx, src/features/environmentCreate/components/CreateEnvironmentPackagesTableRow.tsx, src/features/environmentCreate/components/EnvironmentCreate.tsx, src/features/environmentCreate/components/Specification/SpecificationCreate.tsx, src/features/environmentCreate/components/index.ts, src/features/environmentCreate/environmentCreateSlice.ts, src/features/environmentCreate/index.ts, src/features/environmentDetails/components/EnvironmentDetails.tsx, src/features/environmentDetails/components/EnvironmentDetailsHeader.tsx, src/features/environmentDetails/components/Specification/SpecificationEdit.tsx, src/features/environmentDetails/environmentDetailsSlice.ts, src/features/metadata/components/EnvMetadata.tsx, src/features/requestedPackages/components/AddRequestedPackage.tsx, src/features/requestedPackages/components/RequestedPackagesEdit.tsx, src/features/requestedPackages/components/RequestedPackagesTableRow.tsx, src/features/requestedPackages/requestedPackagesSlice.ts, src/features/requestedPackages/stories/RequestedPackagesEdit.stories.tsx, src/features/yamlEditor/components/editor.tsx, src/store/rootReducer.ts, src/utils/helpers/index.ts, src/utils/helpers/updatePackagesWithConstraints.ts
Note for @telamonian 
There were a lot of bugs that emerged from environment creation and edition functionality. What I tried to accomplish with this PR is to remove some of the prop drilling and heavy local state that we had and move that in redux so we can have a bit easier time extending things and having fewer bugs. There were cases where one component was doing things that it should not be responsible for and it was hard to develop it or prevent bugs since there were many props drilled and it was used in multiple places. 
I was not able to do everything exactly how I would want it since the app was growing on the old code for weeks.
=> environment composer refactor

src/utils/helpers/buildMapper.ts
When a build is queued, its status in the list of builds is now "Queued" instead of "Building"
=> Fix build status for queued builds

.github/workflows/build-push-image.yml, Dockerfile
This PR adds a Github-Action that builds and pushes the conda-store-ui image to GHCR. 
> NOTE: the push will only be triggered on commits to `main`, building the image will occur on all PRs that touch the dockerfile or workflow file.
This action requires an access token that will need to be added as a secret: `GHCR_TOKEN` 
Something I don't have permissions to do.
Lastly, when the GHCR registry is first created, it is private, we will just need to flip it over to public. 
cc @pierrotsmnrd
=> Add gha to build/push image to ghcr

Dockerfile
Extend yarn timeout to avoid `There appears to be trouble with your network connection. Retrying...` warnings messages and failures when running the docker stack
=> Extend yarn timeout

src/features/requestedPackages/requestedPackagesApiSlice.ts
The fix uses an API parameter that makes the results be distinct on names, so no more partial results and need to parse multiple pages.
This works with the current version of conda-store (0.4.12) as well as the next release with DB rework and performances improvements.
=> fix #93 : List of packages names is incomplete

src/components/Popup.tsx, src/features/environmentCreate/components/EnvironmentCreate.tsx, src/features/environmentDetails/components/EnvironmentDetails.tsx, src/features/metadata/components/BuildDropdown.tsx, src/features/metadata/components/EnvBuilds.tsx, src/features/metadata/components/EnvMetadata.tsx, src/features/metadata/metadataSlice.ts, src/features/requestedPackages/components/RequestedPackagesTableRow.tsx, src/features/tabs/components/PageTabs.tsx
- When a new env is created the dropdown should select the new build id and show the new specification data related.
- Avoid blank page when the version and constraint of the package are empty.
=> Fix blank page & update specification area when a new env is created

.github/workflows/push.yml
Add a CI process for generating build artifacts which can be then used by conda-store as assets.
=> Adding webpack bundle to push

src/features/artifacts/components/ArtifactsItem.tsx, src/utils/helpers/artifact.ts, src/utils/helpers/parseArtifactList.ts
When we set `REACT_APP_API_URL` with a relative path like `/conda-store/`, it will return the following error:
> TypeError: Failed to construct 'URL': Invalid base URL
That error happens because the second parameter of `new URL()` should be an absolute path.
To fix that issue, we need to identify when the `REACT_APP_API_URL` is relative. If yes, complete the URL structure, retrieving the existing one from the browser.
=> Fix artifacts URL

src/common/interfaces/NamespaceEnvironments.ts, src/common/models/Namespace.ts, src/features/environments/components/Environments.tsx, src/features/environments/components/EnvironmentsList.tsx, src/features/namespaces/namespacesApiSlice.ts, src/utils/helpers/namespaces.ts, test/environments/EnvironmentList.test.tsx, test/environments/Environments.test.tsx, test/helpers/namespaces.test.tsx, test/testutils.tsx
- If the user is logged in, he should be able to see their primary namespace at the top. The default one is going to be listed in Shared Environments.
- If the user is not logged in, the primary namespace space is not visible, and the default namespace is still appearing in Shared environments.
**Updates and considerations:**
If the user does not have any environments, we are going to always display the default one (empty).
If the user is logged in, we are going to display both namespaces: the primary and the default one.
The user can interact with all the namespaces.
=> User's primary namespace

src/layouts/PageLayout.tsx
If the user has a long username, the sidebar was not fitting and, as a result, the name and the "+" were cut off.
With this approach, we don't need to care about the username's length because any content will affect the sidebar.
This feature was tested with different usernames:
=> Fit the sidebar width according to their content

src/components/VersionSelect.tsx, test/components/VersionSelect.test.tsx
compare-versions will throw an error if it encounters something like '0.5.0.pre'. A quick workaround is to just exclude them from the selection list.
this should fix #204
=> Exclude packages with non-standard versions

src/common/models/Build.ts, src/features/metadata/components/EnvBuilds.tsx, src/features/metadata/components/EnvMetadata.tsx, src/utils/helpers/buildMapper.ts, test/helpers/BuildMapper.test.tsx
- Before we transform the date to display in the dropdown, let's make sure the value for the ended_on prop isn't undefined. If it is undefined, use the scheduled_on prop.
- When you select a new build from the dropdown, the selected one becomes active; this should not happen. The current build ID should remain active until the user changes it. (Feature ready to be merged in #208)
https://user-images.githubusercontent.com/5192743/217296905-cf94126c-883c-4fbf-b2fc-230d6f0466c4.mov
=> validate when ended_on prop  is null

src/features/environmentCreate/components/EnvironmentCreate.tsx, src/features/environmentDetails/components/EnvironmentDetails.tsx, src/features/environmentDetails/environmentDetailsApiSlice.ts, src/features/metadata/components/EnvBuilds.tsx, src/features/metadata/components/EnvMetadata.tsx, src/features/metadata/metadataSlice.ts, src/features/tabs/tabsSlice.ts, test/metadata/EnvBuilds.test.tsx, test/metadata/EnvMetadata.test.tsx
- The feature is only available in edit mode.
- If the user tries to update the environment with a failed build, the button does not appear.
- If the build id selected is the same as the current one, the button does not appear.
The following record can be useful in order to understand the new update environment build id behavior:
https://user-images.githubusercontent.com/5192743/217143425-07ca150f-8e01-4bef-bfb3-07acea7ad3b7.mov
=> Update environment build id by using the dropdown

src/features/environments/components/EnvironmentsList.tsx, src/layouts/PageLayout.tsx
According to this fix, the user should be able to expand all their namespaces and see the environment details without any problem, as the following video shows:
https://user-images.githubusercontent.com/5192743/218556154-babcf978-e59c-4b2a-b737-bb5a55da10f1.mov
=> Fix scrolling left sidebar issue

src/common/interfaces/NamespaceEnvironments.ts, src/common/models/Environment.ts, src/common/models/Namespace.ts, src/features/environmentCreate/components/EnvironmentCreate.tsx, src/features/environmentDetails/components/EnvironmentDetails.tsx, src/features/environmentDetails/components/EnvironmentDetailsHeader.tsx, src/features/environments/components/EnvironmentDropdown.tsx, src/features/environments/components/Environments.tsx, src/features/tabs/tabsSlice.ts, src/utils/helpers/namespaces.ts, test/environmentDetails/EnvironmentDetailsHeader.test.tsx, test/environments/EnvironmentDropdown.test.tsx, test/environments/Environments.test.tsx, test/helpers/namespaces.test.tsx
The endpoint above retrieves the following information: 
```
{
status: "ok",
data: {
authenticated: true,
primary_namespace: "admin",
entity_permissions: {
"default/*": ["environment::read", "namespace::read"],
"filesystem/*": ["environment::read", "namespace::read"],
"admin/*": [
"build::delete",
"environment::delete",
"environment::read",
"environment::update",
"environment:create",
"namespace::create",
"namespace::delete",
"namespace::read"
]
},
entity_roles: {
"default/*": ["viewer"],
"filesystem/*": ["viewer"],
"admin/*": ["admin"]
},
expiration: "2023-02-14T15:19:36+00:00"
},
message: null
};
```
- We are [validating](https://github.com/Quansight/conda-store-ui/compare/main...jujogi:conda-store-ui:feature/readonly-namespaces?expand=1#diff-81e3f09cbe5d43074bb253e5c622de0cb34d37c178070 …
=> Create environments based on the namespaces' permissions.

src/features/channels/components/ChannelsEdit.tsx, src/features/environmentCreate/components/CreateEnvironmentPackages.tsx, src/features/requestedPackages/components/RequestedPackagesEdit.tsx
This old approach to scrolling down when the user wants to add a package/channel was causing an issue inside Jupyter Lab.
Basically, instead of scrolling the component itself, we should scroll the parent element, which has the ability to do that.
https://user-images.githubusercontent.com/5192743/219144950-a7d5852b-0a57-4300-893f-b1911bb980ae.mov
=> remove smooth scrolling when the user wants to add a package

.github/workflows/build.yml, .github/workflows/deploy.yml
This PR adds actions to:
* Build on every push to main and every PR
* Uploading when a new release is cut and tagging said release on npm. For this purpose we should follow the nomenclature of 'v0.0.X-rcY' where X and Y are digits corresponding to the version and release candidate. The package will then be tagged the same, making it easier to install.
=> adds build and deploy to actions

package.json
This PR removes the package.json line that removes the conda-store tarball, so we can actually upload it.
=> Keep conda-store-ui tarball

package.json
Thie PR ensures that the dist folder is included in the package that is uplaoded to npm.
=> remove removal of dist/ folder during yarn pack

src/layouts/PageLayout.tsx
It seems like using `vh` as the unit size to define a full height does not work as we expected inside the extension. 
The change is to define the two rows with 100% height.
https://user-images.githubusercontent.com/5192743/219706863-2c47b82f-38ed-42f0-9dd7-a6514a002d84.mov
https://user-images.githubusercontent.com/5192743/219706970-02c8ecc2-ff50-4e9d-b027-71d99478d2fd.mov
=> Fix scrolling issue in JupyterLab extension

package.json, src/features/requestedPackages/components/AddRequestedPackage.tsx, yarn.lock
The API returns results in alphabetical order. Using match-sorter, if a user searches for 'pandas', we'll give 'pandas' as the first result instead of 'airflow-with-pandas'
Fixes #217
=> Better sorting for package search results

test/helpers/BuildMapper.test.tsx
This test was failing outside of UTC-5. Instead of worrying about timezones, let's just check part of the name string. We're still confirming that the value is populated and not erroring.
=> Stabilize a tz-sensitive test

src/docs/markdown/CONFIGURATION.md, src/preferences.tsx
`conda-store-ui` is configurable **at compile time** thanks to the `.env` file
This PR adds a **runtime** configuration that can be defined right before loading the bundled app, for instance like  : 
```html
<script>
var condaStoreConfig = {
REACT_APP_AUTH_METHOD: "cookie",
REACT_APP_AUTH_TOKEN: "",
REACT_APP_STYLE_TYPE: "grayscale",
REACT_APP_SHOW_LOGIN_ICON: "true",
REACT_APP_API_URL: "http://localhost:5000/conda-store",
REACT_APP_LOGIN_PAGE_URL: "http://localhost:5000/conda-store/login?next=",
};
</script>
```
=> Runtime configuration

src/features/requestedPackages/components/RequestedPackageList.tsx
Fixes #232 
This PR,
As this change affects the UI, this are the screenshots on how it changes.
**Before**
**After**
In case the windows is too small to show all the elements, a horizontal scrollbar appears
=> Fix size of requested packages widget

src/features/channels/components/Channel.tsx, src/features/dependencies/components/DependenciesItem.tsx
Fixes #266.
**grayscale**
**green-accent**
**grayscale**
**green-accent**
The decision was to remove the square icon given that it made it seem as a checkbox.
=> Remove square icon in dependencies and channel widgets

src/features/artifacts/components/ArtifactList.tsx, src/features/artifacts/stories/ArtifactsList.stories.tsx, src/utils/helpers/artifact.ts, test/artifacts/ArtifactItem.test.tsx, test/artifacts/ArtifactsList.test.tsx, test/helpers/artifact.test.tsx
Fixes #195.
- Changes the artifact link names to the specified names in the issue
- Adjust the tests to the changes
**Before**
**After**
- The prefix `Show` will open in a new tab the requested artifact
- The prefix `Download` will ask the user the desired path to download the requested artifact
A follow up PR will be made once the design system for links is determined.
=> Change artifact link names

src/features/environmentDetails/components/EnvironmentDetails.tsx, src/features/environmentDetails/components/Specification/SpecificationEdit.tsx, src/features/metadata/components/EnvBuilds.tsx, src/features/metadata/components/EnvMetadata.tsx, src/features/requestedPackages/components/RequestedPackagesEdit.tsx, src/features/requestedPackages/components/RequestedPackagesTableRow.tsx
Part of #269.
- Changes the label in edit mode so that the user understands that changing an option in the combobox will change the default build
**Before**
**Now**
Please note that the screenshots were taken with different themes
=> ENH - Improve default build selection workflow

src/features/environmentCreate/components/EnvironmentCreate.tsx
=> Wrap env description in quotes

src/features/artifacts/components/ArtifactList.tsx, src/features/environmentCreate/components/Specification/SpecificationCreate.tsx
Fixes #264.
- Improves the default yaml environment template
- Removes an unnecessary console.log that was merged in a previous PR
**Before**
**Now**
=> Improve default yaml environment template

src/utils/helpers/buildMapper.ts
Fixes #250.
- Add build time in the `Status` field when build is completed
=> FEAT - Display build time for environments

README.md
I noticed that we had a link to the jupyterlab conda store repo that was pointing to the wrong place. This is a quick fix.
=> Update jupyterlab-conda-store link in README.md

.github/workflows/release.yml, RELEASE.md
While the current workflow works in the sense of making a release to npm - it throws an error as there is no `.npmrc` file present in the runner. 
This PR ensures node is correctly set up and the file is created.
=> MAINT - Update release workflow - configure node

src/features/artifacts/components/ArtifactsItem.tsx, src/theme.tsx
Part of #288
- Implements the design system links
**Default**
**Hover**
**Focus**
=> Implement design system links

.env.example, src/docs/markdown/CONFIGURATION.md, src/preferences.tsx
See https://github.com/conda-incubator/conda-store/issues/651.
=> Use green UI by default

src/common/models/Build.ts, src/features/environmentCreate/components/EnvironmentCreate.tsx, src/features/metadata/components/EnvBuilds.tsx, src/utils/helpers/buildMapper.ts
Companion PR for https://github.com/conda-incubator/conda-store/pull/653
=> Expose `status_info` in the UI

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml, Dockerfile, README.md, environment_dev.yml, package.json
Closes #323
I am unsure why we were pinning to `16.x` on nodejs in multiple places (there was no `engine` entry in the `package.json`, and I have been building/testing this project with node 20 with no problems.
- Bumps node version in GitHub workflows
- Bumps base node Docker image
- Bumps node version in `dev_environment.yml`
- Rename conda env (give a more descriptive name)
- Document use of conda env in README (related to #338 - though this needs documenting in the conda-store-ui docs too)
=> MAINT -  Bump nodejs version

test/playwright/conftest.py, test/playwright/test_ux.py
Fixe flaky playwright tests. 
This adds a custom default timeout for all tests which is much longer than the default of 5 seconds. This allows the page to load and the backend to catchup before raising an error. 
- adds 30s default timeout for all playwright tests
=> Add default timeout

src/features/requestedPackages/components/AddRequestedPackage.tsx, src/theme.tsx, test/components/BlockContainerEditMode.test.tsx, test/environmentCreate/SpecificationCreate.test.tsx, test/environmentDetails/SpecificationEdit.test.tsx, test/environments/EnvironmentList.test.tsx, test/testutils.tsx
I couldn't find any GitHub issue about the Jest tests being broken.
- Allows `yarn test` to run and exit without errors
- (But does not fix any of the uncaught errors that get generated during test execution and logged to the console but do not actually cause any of the tests to fail.)
=> Tests pass (but with console errors and warnings)

src/features/environmentDetails/components/EnvironmentDetailsHeader.tsx
Fixes #203.
- Enable `showEditButton` props to disable the ability to edit locked environments
Now the edit button is disabled if the environment is locked,
=> Disable ability to edit locked environments

src/features/environments/components/EnvironmentDropdown.tsx, src/styles/StyledIconButton.tsx, test/environmentCreate/CreateEnvironmentPackagesTableRow.test.tsx, test/environmentDetails/SpecificationEdit.test.tsx, test/environments/EnvironmentList.test.tsx, test/requestedPackages/RequestedPackagesTableRow.test.tsx
I'm not sure if there's already a GitHub issue for this, but see https://github.com/conda-incubator/conda-store-ui/pull/357#issuecomment-1918358880
This PR fixes things so that there are no warnings when running `yarn test`.
Note: PR #357 fixed the **errors**, not the warnings.
- [n/a] Did you update the documentation (if required)?
=> Fix test warnings 

.github/ISSUE_TEMPLATE/release.md
As @pavithraes and I worked on the release, we found a couple of broken links. This PR fixes them.
=> BUG - Fix release template links

RELEASE.md
Fixes # .
Removes the manual npm publish steps. This is not required because the release GitHub action has the relevant permission to publish to npm, and it will auto-triggerred when a new tag is created with a release on github.
=> Remove manual npm publish step

.env.example, docker-compose.yml
Set it to the last version in which the server-vendored version of the UI was still working (i.e., 2023.3.1 at localhost:8080/conda-store).
Does not fix, but it is tangentially related to:
- https://github.com/conda-incubator/conda-store-ui/issues/408.
=> Bump default CONDA_STORE_SERVER_VERSION

.github/workflows/build.yml, .github/workflows/javascript-tests.yml, .github/workflows/pages.yml, .github/workflows/release.yml, .github/workflows/test.yml
There are several warnings in our CI about deprecations due to outdated actions.
This PR
- bumps relevant actions to their latest major release
- adds some cosmetic changes to keep workflows consistent
=> MAINT - Update actions

src/features/yamlEditor/components/editor.tsx, test/playwright/test_ux.py
Hoping this will fix failing jobs on GitHub.
Ideally, we would have shorter timeouts for local dev and longer timeouts for CI, but I'm not sure how to do that off the top of my head.
=> Increase Playwright timeouts, robustify YAML editor interaction

src/features/requestedPackages/components/RequestedPackageList.tsx, src/styles/StyledAccordionDetails.tsx
- Unnecessary vertical scroll bars on the tables labeled "Requested packages" and "Channels"
- Unnecessary horizontal scroll bar on "Requested packages" table
No more unnecessary scroll bars.
=> Remove unnecessary scroll bars from specification tables

.env.example, src/App.tsx, src/preferences.tsx
This change should have been made with [Bye tabs, hi URLs #389](https://github.com/conda-incubator/conda-store-ui/pull/389). That PR introduced URL routing to the app, assuming that the React app would always be mounted in the browser at the root path, "/". But the Conda Store server supports a URL prefix, which means that the UI app in such deployments, might be mounted at some path other than root, such as "/conda-store", for example loading the UI at https://example.com/conda-store instead of just https://example.com.
- Introduces a new configuration variable: REACT_APP_URL_BASENAME (which maps directly to React Router browser router `opts.basename`)
=> Add config option REACT_APP_URL_BASENAME

.github/ISSUE_TEMPLATE/release.md, package.json
Fixes https://github.com/conda-incubator/conda-store-ui/issues/434
Now that the release for conda-store-ui is completed, the last step is to bump the package version.
=> DEV - Bump conda-store-ui version - post release

src/layouts/PageLayout.tsx, src/preferences.tsx, test/playwright/memory-router-test.html, test/playwright/test_react_router.py, webpack.config.js
Note to reviewer: before reviewing this PR, check out the comments on https://github.com/gabalafou/conda-store-ui/pull/1.
This PR contains the tests for https://github.com/conda-incubator/conda-store-ui/pull/429.
It is a separate PR because it makes significant changes to the React app code.
I believe that these changes are not only necessary to enable these tests but that they also fix a long-standing bug that I guess we did not even realize that we had. 
The bug is that we say in our docs that the UI app can be configured "[at runtime, using condaStoreConfig](https://conda.store/conda-store-ui/how-tos/configure-ui)." But before this PR, the app code would choose the [build-time over run-time config](https://github.com/gabalafou/conda-store-ui/pull/1#discussion_r1801601380). It would …
=> Add React router tests

src/utils/helpers/buildMapper.ts, test/helpers/BuildMapper.test.tsx, test/playwright/conftest.py, test/playwright/test_ux.py
This PR is the front-end companion to the following server PR:
- https://github.com/conda-incubator/conda-store/pull/747
- Adds "CANCELED" status to the front end
- Adds additional status to "Active" build if the build has ended but the status is not "COMPLETED"
- Rationale: it was weird to me to see a canceled build marked "Active" in the dropdown. Yes, it is the current build, but it's broken and I think this should be a bit more obvious in the UI.
This screenshot shows how a canceled build appears in the UI. Note that this build is not the current build. The dropdown displays "October 22nd, 2024 - 6:19 PM  - Canceled." And on the next line we have "Status: Canceled":
This screenshot shows how the current build appears in the dropdown if it was canceled. The line for …
=> Add "canceled" build status

docker-compose.yml
Conda-store 2024.11.1 was recently released. This updates the conda-store-ui docker-compose files to use this most recent version.
ref: https://github.com/conda-incubator/conda-store/issues/967
=> Bump conda-store server version

src/features/artifacts/components/ArtifactsItem.tsx, src/features/metadata/components/EnvBuildStatus.tsx, src/hooks.ts, src/utils/helpers/parseArtifactList.ts, test/artifacts/ArtifactsList.test.tsx
Fixes:
- Fixes https://github.com/conda-incubator/conda-store/pull/995.
Supersedes:
- https://github.com/conda-incubator/conda-store-ui/pull/442
- https://github.com/conda-incubator/conda-store/pull/997
This is [not the first time the build artifact links have been broken](https://github.com/conda-incubator/conda-store-ui/pull/185). The solution in this pull request is robust to both the recent breakage and the older one.
=> Fix links to build artifacts

docker-compose.yml
A new version of the conda-store/conda-store-server docker image is pushed to the latest tag whenever a pr is merged to main (on conda-incubator/conda-store).
By setting the default docker compose setup to pull the latest image, developers will always be using the most up to date version of conda-store. Developers can set a specific version they want to test against by setting  `CONDA_STORE_SERVER_VERSION`
=> Always use the latest conda-store unless a version is provided
