Dockerfile
README.md
docker-compose-dev.yml

Latest version of the readme, and dockerfiles to run the complete stack locally.

improvement in readme and dockerfiles

---

src/features/environmentDetails/components/EnvironmentDetails.tsx
src/features/metadata/components/EnvBuilds.tsx
src/features/metadata/components/EnvMetadata.tsx
src/features/metadata/metadataApiSlice.ts
src/utils/helpers/buildMapper.ts

use scheduled_on prop if the build status is **building**

When a build is building, a wrong date is shown

---

package.json
src/utils/helpers/buildMapper.ts
yarn.lock

**Before:** 
**After: Colombian timezone and AM/PM details**

show date according user's timezone

---

src/features/channels/components/ChannelsEdit.tsx
src/features/environmentCreate/components/CreateEnvironmentPackages.tsx
src/features/environmentCreate/components/Specification/SpecificationCreate.tsx
src/features/environmentDetails/components/Specification/SpecificationEdit.tsx
src/features/requestedPackages/components/RequestedPackagesEdit.tsx
src/styles/StyledButtonPrimary.tsx

@pierrotsmnrd This fix is needed so we don't get this error printed out in the console 
https://reactjs.org/warnings/unknown-prop.html

fix dom attr error

---

src/features/environmentDetails/components/EnvironmentDetails.tsx
src/features/environments/components/Environments.tsx
src/features/environments/stories/Environments.stories.tsx
src/layouts/PageLayout.tsx
src/utils/helpers/index.ts
src/utils/helpers/polling.ts

Polling added every 2 seconds.

Refresh the list of namespaces and environments 

---

README.md

Update in Readme : added UI URL and login icon

Update in Readme : added UI URL and login icon

---

src/features/artifacts/ArtifactsApiSlice.ts
src/features/dependencies/dependenciesApiSlice.ts
src/features/environmentDetails/environmentDetailsApiSlice.ts
src/features/environments/environmentsApiSlice.ts
src/features/metadata/metadataApiSlice.ts
src/features/namespaces/namespacesApiSlice.ts
src/features/requestedPackages/requestedPackageVersionApiSlice.ts
src/features/requestedPackages/requestedPackagesApiSlice.ts
src/layouts/PageLayout.tsx
src/preferences.tsx

- Add a trailing slash to each endpoint to avoid redirects.
- Users can define the app style by editing the JupyterLab settings.
- Fill the entire app background with white.

Fix Jupyterlab integration issues

---

docker/assets/conda_store_config.py

Builds were failing using the docker-compose of the repository, because the config file was not up to date.

Update config to fix builds

---

src/features/artifacts/components/ArtifactList.tsx
src/features/artifacts/stories/ArtifactsList.stories.tsx
src/features/dependencies/components/Dependencies.tsx
src/features/dependencies/dependenciesApiSlice.ts
src/features/environmentDetails/components/EnvironmentDetails.tsx
src/features/environmentDetails/components/Specification/SpecificationReadOnly.tsx
src/features/metadata/components/BuildDropdown.tsx
src/features/metadata/components/EnvBuilds.tsx
src/features/metadata/components/EnvMetadata.tsx

Some improvements were made in this PR:
- Refresh periodically the installed dependencies. If they are not empty, stop making new requests.
- If the artifact list already has the Docker manifest, stop making new requests.
- The build dropdown was refactored in order to improve the way to get the status of the build.
**Note: The packages installed as dependencies are now always present. Just show a loader while it takes the data.**

Refresh dependencies after created an env

---

package.json

Update package.json for release 0.0.1-alpha.9

Release 0.0.1-alpha.9

---

package.json

Release 0.0.1-alpha.11

---

src/features/requestedPackages/components/AddRequestedPackage.tsx

In this PR, we're fixing the following issues:
- (#191) Wait until the user enters at least two characters before calling the package endpoint.
- (#192) Change the way to add a package. Before, the user had to click outside the component to add it. Now, the user can click the package from the dropdown options or use the Enter keyboard as well.
This video can help you understand the new behavior:
-
https://user-images.githubusercontent.com/5192743/217600309-c2dadbf8-f03b-499b-949d-620b174763ef.mov

change the way to select an option from the autocomplete dropdown

---

.github/workflows/deploy.yml

This PR ensures that the package is properly packaged so that other applications can use it properly. It fixes the GitHub actions to do this. cc: @costrouc

fix yarn package

---

src/common/config/labels.ts
src/components/Dialog.tsx
src/components/index.tsx
src/features/environmentCreate/components/EnvironmentCreate.tsx
src/features/environmentDetails/components/EnvironmentDetails.tsx
src/features/environmentDetails/components/Specification/SpecificationEdit.tsx
src/features/environmentDetails/environmentDetailsApiSlice.ts
src/layouts/PageLayout.tsx

- Implement deletion of environments feature
- Centralize feedback alerts
- Create dialog component
https://user-images.githubusercontent.com/5192743/219426765-d4639740-77c9-4359-a83c-dbd25f0626a9.mov

Deletion of environments

---

README.md

This PR updates the README with release instructions

add instructions for releases

---

.github/workflows/pages.yml
README.md

This PR adds badges for the github actions to the readme. I'll be merging this in once documentation is reworked.

update readme with badges

---

README.md
src/docs/markdown/INSTALL.md
src/docs/markdown/START.md

This PR is part of https://github.com/conda-incubator/conda-store-ui/issues/254
This PR,

Update repository URLs

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/general_issue.yml
.github/PULL_REQUEST_TEMPLATE.md

This PR is part of https://github.com/conda-incubator/conda-store-ui/issues/254
This PR,

Add issue templates

---

.github/PULL_REQUEST_TEMPLATE.md

Ref: https://github.com/conda-incubator/conda-store/pull/555

Typo fixes in `PULL_REQUEST_TEMPLATE.md`

---

LICENSE

Addresses https://github.com/conda-incubator/conda-store/issues/399
- Updates license attribution after the move to conda-incubator

Update LICENSE attribution

---

src/features/dependencies/stories/Dependencies.stories.tsx
src/features/environments/stories/Environments.stories.tsx
src/features/requestedPackages/stories/RequestedPackagesEdit.stories.tsx

Fixes #234.
This pull request fixes broken stories for the following components,
- dependencies
- environments
- requestedPackagesEdit
Now the stories render as expected,
**dependencies**
**environments**
**requestedPackagesEdit**

Mock `store` with Provider for broken stories

---

README.md
package.json

REL - 2023.9.1

---

.github/workflows/release.yml

ENH - Update release workflow

---

.github/workflows/release.yml
package.json

- Fix action workflow
- Bump version (hotfix)

:bookmark: Bump release

---

.github/workflows/release.yml

BUG -  Fix release workflow

---

.github/workflows/release.yml
README.md

Fixes # .
- updates readme
- change workflow to tag creation

MAINT - Updates to docs and workflows

---

.github/workflows/release.yml
package.json

Changes made:
- Update yarn syntax
- Bump version for pre-release

MAINT - Update yarn syntax in workflows

---

.github/workflows/release.yml

Revert yarn

---

.github/ISSUE_TEMPLATE/release.md
.github/workflows/release.yml
RELEASE.md
package.json

Fixes # .
- Adds updated release instructions and workflows
- Bumps version in package

ENH - Update release process 

---

test/environments/EnvironmentSearch.test.tsx

Fixes #318.
- Fixe the environment search tests

Fix environment search tests

---

test/playwright/test_ux.py

Attempt to fix a flaky playwright test

---

README.md

- Fixes broken link to logo (from recent changes in conda-store docs)
- Makes minor improvements to readme

MAINT - Miscellaneous improvements to readme

---

.github/workflows/release.yml

This PR should fix the authentication + publishing issues in the CI.

DEV -  Add scope to release action

---

src/features/environments/components/EnvironmentDropdown.tsx

Fixes #127.
This pull request adds text "New" to the button for creating a new environment.
- [n/a] Did you update the documentation (if required)?
- [n/a] Did you add/update relevant tests for this change (if required)?

Text label for add new environment

---

package.json

Addresses #378
- Creates a release

REL - 2024.3.1

---

README.md
src/features/environments/components/Environments.tsx

This pull request updates some old links to conda-store & UI docs
Noticed during a user research session w/ `@smeragoel` and Prashant Tiwari

Update links to conda-store docs

---

package.json

Partially addresses #403.
This PR marks the 2024.6.1 release.

REL - 2024.6.1

---

src/index.tsx

Fix warning: export 'IPreferences' not found

---

package.json

Part of #426 - this bumps conda-store-ui so we can publish a release candidate

REL - 2024.9.2-rc1

---

package.json

ref https://github.com/conda-incubator/conda-store-ui/issues/444

Bump version for dev
